service: serverless-ts-webpack-template
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  timeout: 30

functions:
  hello:
    handler: src/main.start
    events:
      - http:
          path: test
          method: get

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes
  - serverless-offline


custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: 'npm'